version: '3.3'
services:
  adminer:
    image: adminer:latest
    ports:
      - 9080:8080
    networks:
      - webnet
  postgres:
    image: postgres:11
    volumes:
      - data-volume:/data/db
    ports:
      - 9432:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    networks:
      - webnet
networks:
  webnet:
volumes:
  data-volume:
